/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CopyPathPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  showNotice: true,
  quoteStyle: "single"
};
var CopyPathPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("copy", "Copy Path", () => {
      this.copyActiveFilePath();
    });
    this.addCommand({
      id: "copy-active-file-path",
      name: "Copy active file path",
      callback: () => {
        this.copyActiveFilePath();
      }
    });
    this.addCommand({
      id: "copy-selected-files-path",
      name: "Copy selected files path",
      callback: () => {
        this.copySelectedFilesPaths();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle("Copy path").setIcon("copy").onClick(() => {
            this.copyPathsToClipboard([file]);
          });
        });
      })
    );
    this.registerEvent(
      this.app.workspace.on("files-menu", (menu, files) => {
        menu.addItem((item) => {
          item.setTitle("Copy paths").setIcon("copy").onClick(() => {
            this.copyPathsToClipboard(files);
          });
        });
      })
    );
    this.addSettingTab(new CopyPathSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Copy the path of the currently active file
   */
  copyActiveFilePath() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      this.copyPathsToClipboard([activeFile]);
    } else {
      new import_obsidian.Notice("No active file");
    }
  }
  /**
   * Copy paths of selected files in file explorer
   */
  copySelectedFilesPaths() {
    const selectedFiles = this.getSelectedFilesFromExplorer();
    if (selectedFiles.length > 0) {
      this.copyPathsToClipboard(selectedFiles);
    } else {
      this.copyActiveFilePath();
    }
  }
  /**
   * Get selected files from the file explorer
   */
  getSelectedFilesFromExplorer() {
    var _a, _b;
    const fileExplorer = this.app.workspace.getLeavesOfType("file-explorer")[0];
    if (!fileExplorer) {
      return [];
    }
    const explorerView = fileExplorer.view;
    if (explorerView && explorerView.fileItems) {
      const selectedFiles = [];
      for (const [path, item] of Object.entries(explorerView.fileItems)) {
        if ((_b = (_a = item.selfEl) == null ? void 0 : _a.classList) == null ? void 0 : _b.contains("is-selected")) {
          const file = this.app.vault.getAbstractFileByPath(path);
          if (file) {
            selectedFiles.push(file);
          }
        }
      }
      return selectedFiles;
    }
    return [];
  }
  /**
   * Recursively collect all file paths from files and folders
   */
  collectAllPaths(items) {
    const paths = [];
    for (const item of items) {
      if (item instanceof import_obsidian.TFile) {
        paths.push(item.path);
      } else if (item instanceof import_obsidian.TFolder) {
        paths.push(item.path);
      }
    }
    return paths;
  }
  /**
   * Format paths with quotes
   */
  formatPaths(paths) {
    const quote = this.settings.quoteStyle === "single" ? "'" : '"';
    return paths.map((p) => `${quote}${p}${quote}`).join(", ");
  }
  /**
   * Copy paths to clipboard
   */
  async copyPathsToClipboard(files) {
    const paths = this.collectAllPaths(files);
    if (paths.length === 0) {
      new import_obsidian.Notice("No paths to copy");
      return;
    }
    const formattedPaths = this.formatPaths(paths);
    try {
      await navigator.clipboard.writeText(formattedPaths);
      if (this.settings.showNotice) {
        const count = paths.length;
        const message = count === 1 ? "Path copied" : `${count} paths copied`;
        new import_obsidian.Notice(message);
      }
    } catch (err) {
      new import_obsidian.Notice("Failed to copy to clipboard");
      console.error("Copy failed:", err);
    }
  }
};
var CopyPathSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Copy Path Settings" });
    new import_obsidian.Setting(containerEl).setName("Show notification").setDesc("Show a notification when paths are copied").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showNotice).onChange(async (value) => {
        this.plugin.settings.showNotice = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Quote style").setDesc("Choose quote style for paths").addDropdown(
      (dropdown) => dropdown.addOption("single", "Single quotes ('path')").addOption("double", 'Double quotes ("path")').setValue(this.plugin.settings.quoteStyle).onChange(async (value) => {
        this.plugin.settings.quoteStyle = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Hotkeys" });
    containerEl.createEl("p", {
      text: "Configure hotkeys in Obsidian Settings \u2192 Hotkeys. Search for 'Copy Path' to find available commands:"
    });
    const commandList = containerEl.createEl("ul");
    commandList.createEl("li", { text: "Copy active file path - Copy the path of the currently open file" });
    commandList.createEl("li", { text: "Copy selected files path - Copy paths of selected files in file explorer" });
  }
};
